### ISSUE TITLE
Rank is not changing. 

### ISSUE THREAD

**Issue by c4retro** [BF2Statistics/ASP#12]
I get up to the correct xp but my rank wont change, however i get medals and all that. everything else appears cool except for that.

**Comment by wilson212** [comment]
Enable rank checking in the ASP. To do this, login to the ASP admin page, then click "System" -> "Edit Configuration". Under the "Stats Processing Options" section, you will see the option to enable "Rank Checking".

**Comment by wilson212** [comment]
Please update to version 3.1.0 and let me know if this issue remains!
