### ISSUE TITLE
looks like its something hokey with the dabase permissions  im looking but i cant find it

### ISSUE THREAD

**Issue by NAW-Kano** [BF2Statistics/ASP#16]
SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'nawadmin'@'%' (using password: YES)

looks like its something hokey with the dabase permissions

im looking but i cant find it

**Comment by wilson212** [comment]
This specific error is telling you that the database password is incorrect, or the remote IP address isn't authorized to access the MySQL database.
