### ISSUE TITLE
error in server admin of  manager snapshots

### ISSUE THREAD

**Issue by bfspy2016** [BF2Statistics/ASP#2]
An Unhandled Exception has occurred

Error Description

The given key was not present in the dictionary: prefix 

Error Details
Type: Exception
Code: 0
File: D:\www\Apache2.4.33\htdocs\ASP\system\framework\Collections\Dictionary.php
Line: 206

Stack Trace
/system/framework/Collections/Dictionary.php @ line 334: 
System\Collections\Dictionary->itemAt('prefix')

/frontend/modules/snapshots/models/SnapshotsModel.php @ line 58: 
System\Collections\Dictionary->offsetGet('prefix')

/frontend/modules/snapshots/Snapshots.php @ line 40: 
SnapshotsModel->getSnapshots('unauthorized')

(unknown file) @ line 0: 
Snapshots->index()

/system/System.php @ line 334: 
ReflectionMethod->invokeArgs(Snapshots(), array(0))

/system/System.php @ line 258: 
System::LoadModule('snapshots', 'index', array(0))

/system/System.php @ line 54: 
System::HandleAdminRequest()

/index.php @ line 47: 
System::Run()

**Comment by wilson212** [comment]
Thanks for pointing this out! I will get it fixed ASAP

**Comment by wilson212** [comment]
All fixed in the new update that has been pushed to the Respitory.
