### ISSUE TITLE
mysql errors

### ISSUE THREAD

**Issue by bfspy2016** [BF2Statistics/ASP#3]
The table "player_award" of Database "schema.sql"  errors  when it is established for:
FOREIGN KEY(`player_id`) REFERENCES player(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(`award_id`) REFERENCES award(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY(`round_id`) REFERENCES round(`id`) ON DELETE RESTRICT ON UPDATE CASCADE

I built it manually and I suspect that different versions of MySQL caused it.

**Comment by bfspy2016** [comment]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'round(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET' at line 13

**Comment by bfspy2016** [comment]
[2018/12/25 14:47:14]	ERROR: [GpcmClient.CreateNewUser] An error occured while trying to create a new User account :: Unknown column 'rank' in 'field list'

**Comment by wilson212** [comment]
Thanks for this! I will work on getting these issues fixed asap

**Comment by wilson212** [comment]
All fixed as of the latest pushes to the REPO. The SQL runs just fine mate, no issues here on a fresh empty database!
