### ISSUE TITLE
After saving a new player, viewing the player returns 404

### ISSUE THREAD

**Issue by archangelnl** [BF2Statistics/ASP#5]

**Comment by wilson212** [comment]
Is your ASP available over the internet? I just did some tests over at the NAW ASP and had no issues with saving players and viewing them afterwards.

What internet browser are you using? Is there anything in the php_errors.log/asp_debug.log files?

**Comment by archangelnl** [comment]
It's not with saving players as far as I know, it's when you add a new player and want to view their stats afterwards.
