### ISSUE TITLE
When enabling bots, the received player ID is invalid

### ISSUE THREAD

**Issue by archangelnl** [BF2Statistics/ASP#6]
This might be more related to the python scripts running, but the server itself lags a lot and the debug logs for python show this:

`Retrieving Profile ID (Blitz25 [IDFA]) via HTTP/1.1 miniclient
URI: /ASP/getplayerid.aspx?nick=Blitz25%20[IDFA]&ai=1
Received PID data is INVALID, length 35`

But when visiting the web page, it does output some data:

`O
H	pid
D	2900137
$	13	$`

**Comment by wilson212** [comment]
SO I was not very clear on the installation instructions, but you must manually add the bots. Here is how you do so:

1. Go to "Player Manager" in the ASP.
2. Click the button labeled "Import Bot Players".
3. You must now open the fil viewer, and vavigate to your bf2 server folder, and traverse "mods/bf2/ai/botNames.ai" file and click open.

All of your bots will now be imported and assigned player id numbers! I apologize for not including this in the install instructions!

**Comment by archangelnl** [comment]
No that's the thing, they seem perfectly added to me as I can find the bot in the ASP's player list, restarted the master server and such as well but it still seems to throw me the same error as above.

**Comment by wilson212** [comment]
Silly question, but did you modify the http_ settings BF2StatisticsConfig.py to match that of your setup? Also, you need to have your hosts' redirects enabled!

Look into this program (that I created) to have those redirects added programmatically: http://bf2statistics.com/resources/battlefield-2-gamespy-redirector.8/

**Comment by wilson212** [comment]
Is this all localhost and running on the same machine?

**Comment by wilson212** [comment]
If the length is 24, that that is a success! Here is a successful entry in my access.log:

"GET /ASP/getplayerid.aspx?nick=R.%20Smedberg&ai=1 HTTP/1.1" 200 24

**Comment by archangelnl** [comment]
It is not, the ASP / master & login server are sitting on one virtual machine with a public IP, and the game server is sitting on the other with another public IP.

That said with the length being 24 at least that is a success, but the error between Python and ASP still remains

**Comment by wilson212** [comment]
Is the bf2 server using a modified hosts file as well (or a hosts.ics)? In order for the bf2 server to be able to talk your master server, it will need to be redirected just like a bf2 client would be.

**Comment by archangelnl** [comment]
It's redirected to the master server through hosts.ics, and I can actively see it pop up on the server browser.

**Comment by wilson212** [comment]
You are using an "online" account correct (with a password)? Does this issue exist with bot players too (all getplayerid.aspx call fail), or just your's as a human player?

**Comment by archangelnl** [comment]
The test account I'm using is indeed a online account yes, the issue is not there for my own account as it gets the ID from my client, the issue is just mainly the bots not getting the ID's, and it keeps retrying over and over, lagging the BF2 server in the process.

**Comment by wilson212** [comment]
Can you do me a favor? 

1) Clear your game log from your bf2 server.
2) Start the server, login and join the game.
3) Exit the game, type "Exit" in the bf2 server console
4) Upload the contents of the game log to pastebin, and post the link here so I can look it over?

**Comment by archangelnl** [comment]
I presume you mean the log file in the python folder right? If so here it is: https://pastebin.com/KFXBn3RZ

**Comment by wilson212** [comment]
That is the log I am looking for yes. I will need some time to figure this out, this is def. an odd issue that I have not run into yet.

**Comment by archangelnl** [comment]
Alright, let me know if you need anything more.

**Comment by wilson212** [comment]
Are you sure that the bots "such as Reaper5000 [bfsp]" are existing in the player table? If you are using a mod, the botNames.ai might have added new names that differ from the vanilla file. If that is the case, ensure you import ALL of the botNames.ai from all the mods you use.

**Comment by archangelnl** [comment]
I get the following result when I enter it in the browser:
O
H	pid
D	2900258
$	13	$

**Comment by wilson212** [comment]
mind sending me your apache access.log over pastebin? I just need the last entries from the server trying to grab player id's

**Comment by archangelnl** [comment]
Here's a snippet of the apache log: https://pastebin.com/5XeijQCt

**Comment by wilson212** [comment]
Alright, a few things I have noticed:

1) is the response length is 50, then the player name does not exist in the database. If the length is 24, a PID is returned in the response, and is successful
2) Some of those 50 responses, I see names like "Ti_GER_arn354 [AIXDevBo". Seems to be missing some characters?
 See request as an example (right from your access log):
"GET /ASP/getplayerid.aspx?nick=Ti_GER_arn354%20[AIXDevBo&ai=1 HTTP/1.1" 200 50
3) I am noticing 2-3 calls for the same player in the exact same second. That is also odd.

**Comment by archangelnl** [comment]
Yes, the python scripts seem to really want to keep querying the pid's for the bot's, so the many requests could be explained by that? As for why it's formatting with the missing characters I'm not sure.

**Comment by wilson212** [comment]
Linux or Windows bf2 server? What version are you using (1.5, 1.41 ??). Playing Aix2 mod correct?

**Comment by archangelnl** [comment]
1.5 based on Windows, and correct!

**Comment by wilson212** [comment]
Have you tried just vanilla and see if you have the same issues? You made need to also import the vanilla botNames.ai

**Comment by archangelnl** [comment]
It was a 2.0 server before, I just reinstalled the server to make sure that it's completely clean, but it still shows the same error as before while getting the bot's PID's

**Comment by wilson212** [comment]
I will install aix 2.0 here in a bit (I have to leave for work soon) and see If possibly I can reproduce the problem with a fresh install. The fact that you can get the PID from the browser, but the server can't is really blowing my mind right now. I have no idea what is causing that.

**Comment by archangelnl** [comment]
Right, so it's not AIX.. I did the following to the python file PlayerManager.py  for debugging and testing purposes

`# If we don't have a PID up to this point, fetch it from ASP back end
		if pid == 0:
			if g_debug: print "Retrieving Profile ID (%s) via HTTP/1.1 miniclient" % str(host.pmgr_p_get("name", self.index))
			
			# URL for retrieving player ID via internal miniclient
			player_nick = string.replace(str(host.pmgr_p_get("name", self.index)), ' ', '%20')
			asp_playerid = '/ASP/getplayerid.aspx?nick=' + player_nick + '&ai=' + str(host.pmgr_p_get("ai", self.index))
			if g_debug: print "URI: %s" % (asp_playerid)
			
			# Fetch Data using miniclient
			data = http_get( http_backend_addr, http_backend_port, asp_playerid )
			
			datalines = data.splitlines()
			print "------------------"
			#print data
			print "Datalines 0: %s" % datalines[0]
			print "Datalines 1: %s" % datalines[1]
			print "Datalines 2: %s" % datalines[2]
			print "Datalines 3: %s" % datalines[3]
			print "end"
			print "------------------"
			
			if data and datalines[1] == 'O':
				if g_debug: print "Received PID data is VALID, length %d" % int(len(data))
				#datalines = data.splitlines()
				pidval = datalines[3].split('\t')
				pid = int(pidval[1])
			else:
				print "Received PID data is INVALID, length %d" % int(len(data))
			
		self.profileid = pid
		return pid
`

That returns:

`Player Manager module initialized
Retrieving Profile ID (S. Flyte) via HTTP/1.1 miniclient
URI: /ASP/getplayerid.aspx?nick=S.%20Flyte&ai=1
------------------
18

O
H	pid
D	2900571
$	13	$

0




Datalines 0: 18
Datalines 1: O
Datalines 2: H	pid
Datalines 3: D	2900571
end
------------------
Received PID data is VALID, length 35
Creating new record for player profileId  2900571
Will retrieve medals from GSI...
roundMedals:  {}
Added player 255, S. Flyte (2900571) to medal/rank checking
Getting STATS for player S. Flyte (2900571)...
Retrieving player STATS via HTTP/1.1 miniclient
ERROR: Received STATS data is NOT VALID, length 926
Getting AWARDS for player S. Flyte (2900571)...
ERROR: Received AWARDS data is NOT VALID, length 76
Unlock module: onPlayerConnect
Player Manager module initialized`

**Comment by wilson212** [comment]
Datalines 0: 18

That is the problem right there.... why is there an 18 there?

**Comment by archangelnl** [comment]
I'm not sure as to why there is a 18 there, but that does indeed look to be the problem yeah.

**Comment by wilson212** [comment]
I will play around with this and see if I can get a fix in the official python release so this does not happen again lol. Your help here has been invaluable! Thank you! Let me know if you have any other questions or issues.

**Comment by wilson212** [comment]
Yea lol, your fix does not work for me:

Retrieving Profile ID (J. Norberg) via HTTP/1.1 miniclient
URI: /ASP/getplayerid.aspx?nick=J.%20Norberg&ai=1
------------------
start
O
H	pid
D	2900045
$	13	$
Datalines 0: O
Datalines 1: H	pid
Datalines 2: D	2900045
Datalines 3: $	13	$
end
------------------
Received PID data is INVALID, length 24
Creating new record for player profileId  0
Retrieving Profile ID (J. Norberg) via HTTP/1.1 miniclient
URI: /ASP/getplayerid.aspx?nick=J.%20Norberg&ai=1

**Comment by archangelnl** [comment]
Yeah, for some reason the 18 in what the php file returns causes the issue for it to not read it correctly, thus needing to go +1, so you request data[0] in the if statement, but with the 18 there that becomes data[1], as for why the 18 is there I have no idea, perhaps it might have to do with it being apache and PHP based off of windows?

**Comment by wilson212** [comment]
Well, I don't think so... Here is what I am using

Apache v2.4.27
PHP: 5.6.31 and 7.2.3

**Comment by archangelnl** [comment]
Running the following setup here:
Windows Server 2016,
Apache v2.4.37,
PHP 7.3,
The only thing that's linux based is the database in this system, which is 10.1.34-MariaDB-0ubuntu0.18.04.1

This is the response headers I get when I open it in the browser:
HTTP/1.1 200 OK
Date: Mon, 31 Dec 2018 22:13:02 GMT
Server: Apache/2.4.37 (Win64) mod_fcgid/2.3.9
X-Powered-By: PHP/7.3.0
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: text/plain; charset=utf-8

**Comment by wilson212** [comment]
Headers look good. Not sure why that 18 is there, but that is def. the issue.

**Comment by JakubMarecek** [comment]
I got same problem, so I digged into a bit more and found the problem.

It looks whole problem is new versions of apache which is probably sending content length in hexadecimal before content.

I created simple python script:
```python
import socket

CRLF = "\r\n"

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.settimeout(30)

sock.connect(("host", 80))
file = sock.makefile("rb")

sock.sendall("GET /ASP/getplayerid.aspx?nick=K.%20Yip&ai=1 HTTP/1.1" + CRLF)
sock.sendall("Host: host" + CRLF)
sock.sendall("User-Agent: GameSpyHTTP/1.0" + CRLF)
sock.sendall("Connection: close" + CRLF) # do not keep-alive
sock.sendall("" + CRLF)
sock.shutdown(1)

print(file.read())
```

and it returns:

```
HTTP/1.1 200 OK
Date: Mon, 04 Apr 2022 06:41:33 GMT
Server: Apache/2.4.38 (Debian)
Upgrade: h2,h2c
Connection: Upgrade, close
Vary: Accept-Encoding
Transfer-Encoding: chunked
Content-Type: text/plain; charset=utf-8

18
O
H       pid
D       2900111
$       13      $
0


```

As you can see there is 18 before content. 18 is hex of 24 in dec and 24 is length of the content. I tested it also on different http request.

As solution is probably adding `http.readline()` to miniclient.py on line 46. But it will be fix for only some users who is getting the extra line before content.

Idk about better fix, maybe apache has special options...
