### ISSUE TITLE
Adding a new unlock returns: Query Failed! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'kit' in 'field list'

### ISSUE THREAD

**Issue by archangelnl** [BF2Statistics/ASP#7]

**Comment by wilson212** [comment]
I need a little bit more detail. How did you get to this error (what page were you one, what button did you push etc etc). Also, posting information from the "/syste/logs/asp_debug.log" will help a lot!

**Comment by wilson212** [comment]
All fixed in the newest push to the Repo!.Thank you for all of your help today, It is much appreciated!
