### ISSUE TITLE
Database is outdated!: Can't update database

### ISSUE THREAD

**Issue by M108** [BF2Statistics/ASP#9]
Getting an error when trying to update the database schema ::
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'score'

**Comment by wilson212** [comment]
Run this query to fix the issue:

INSERT INTO `_version`(`updateid`, `version`) VALUES (30070, '3.0.7');

You may also need to update the index.php:

"define('DB_EXPECTED_VERSION', '3.0.7');"

**Comment by wilson212** [comment]
I am closing this since I have not heard back in over a year. Please download and update to v3.1.0
